name: Friends
version: ${project.version}
main: me.kowlintech.friends.Friends
api-version: 1.13
load: STARTUP
authors: [KowlinMC]
description: A Minecraft Friends plugin developed by Kowlin#4417
commands:
  fadd:
    description: Sends a friend request to someone.
  fgui:
    description: Opens friend management gui.